import type { Metadata } from "next";
import "./globals.css";
import BackgroundSlideshow from "./components/BackgroundSlideshow";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <BackgroundSlideshow />
        {children}
      </body>
    </html>
  );
}
